### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by felixfischer** [wade00/slackmailer#8]
Hi wade00,

I am trying to re-create [what you did](https://medium.com/launchpad-lab/hey-slack-make-me-a-newsletter-3d6bb90a6375) with slackmailer for Launchpad Lab. Could you add some short hints on how to install and use this slack app? I got it installed but cannot get it to work.

Kind regards,
Felix

**Comment by wade00** [comment]
Hi @felixfischer - just saw this issue. Thanks for opening it up!

I haven't configured the app to handle any Slack organization outside of my own, but I'll do some work over the next few weeks to see what I can do to make it more flexible. Are you planning to use it with MailChimp?

**Comment by wade00** [comment]
Hey @felixfischer not sure if you're still interested in this, but I'll be starting some work soon to get Slackmailer more generally available.

If you are interested and you don't mind me asking a question I'd like to get a better idea of how I can make this valuable to you. Would you be looking to wire this up to an existing Mailchimp template or would you be interested in using a set one that comes with the app?

**Comment by felixfischer** [comment]
Hey @wade00 yes, I am still interested. Thanks for digging this up again!

I would prefer a solution where I can bring my own template, or use one of Mailchimp's existing templates (and customize it). Control over design is more valuable to me than ease of use. The less hard-wired the styling, the better, I'd say.

**Comment by wade00** [comment]
Awesome good to know! Thanks for the feedback. I kind of assumed that flexibility was going to be important but it's good to confirm that.

I'll keep you posted on the progress. I'm working on some updates for my company right now and then I'll be working on making this thing configurable.

**Comment by felixfischer** [comment]
This is awesome! I'm looking forward to it!

**Comment by weenjeem** [comment]
Pinging this thread! Just tweeted @launchpadlab to make this more public but looks like it's underway  :)

**Comment by wade00** [comment]
Hey @weenjeem & @felixfischer. So I've been looking into how I can make this open and it'll take some work because the code is tied in with one of our MailChimp templates.

With that said I'm definitely game to give it a shot.

Before I do, though - have either of you used [Revue](https://www.getrevue.co/) or [Goodbits](https://goodbits.io/?) weenjeem I know you mentioned them to me earlier, but if you don't mind I'd like to get your thoughts on those products. They seem really nice, but I did notice that they don't let you use an existing MailChimp template, which I could see being an issue if you've got a mailer you're already sending out to people.

If you guys have a few min I'd love your thoughts on those. I'm just trying to do a little research before I commit to building anything :)

**Comment by aanandhc** [comment]
Hey Wade! I saw that this hasn't been brought up in a while, but I'd love to re-open this. I've tried Revue and Goodbits, and neither is a good fit for my organization. Do you have any updates on making this flexible? Thanks!

**Comment by wade00** [comment]
Hi @aanandhc! Sorry I'm just getting to this. I wasn't planning on making updates to this, but I'll take a look this week and let you know what I can do. I think at the very least I can create a better how-to guide so you can roll your own!

**Comment by wade00** [comment]
@aanandhc sorry for the slow response - things are very busy on my end these days.

I'm not sure when I'll be able to find the time to get Slackmailer public, but sometime in the fall would be a goal for me.

In the meantime it would be pretty simple for me to make a more detailed README if that's something you think would be helpful. It was a pretty simple Sinatra app that made requests to a Slack webhook.

Also - if you don't mind me asking - what didn't work well for you with Revue and Goodbits? Those products are far more fleshed out than this would be anytime soon, but I do think this app does a good job of not trying to do too much.

**Comment by aanandhc** [comment]
@wade00 - would also love to hop on a call in order to talk through it.

**Comment by felixfischer** [comment]
no longer using this software
